apiVersion: apps/v1
kind: Deployment
metadata:
  name: addtask-dep
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: addtask-api
  template:
    metadata:
      labels:
        app: addtask-api
    spec:
      containers:
      - name: addtask-api
        image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
        ports:
        - containerPort: 8000
        env: 
        - name: CONNECTION_STRING
          value: "Server=tcp:sql-dev-todoapp-02211.database.windows.net,1433;Initial Catalog=sqldbdb2212;Persist Security Info=False;User ID=devopsadmin;Password={your_password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"     
